[build]
# disable this if you need some kind of portable build!
# rustflags = "-C target-cpu=native"
# rustflags = "-C target-cpu=x86-64-v3"
rustflags = "-C target-feature=+avx2"

[env]
CARGO_WORKSPACE_DIR = { value = "", relative = true }
