name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
    - name: Cache Linux audio packages
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: libasound2-dev libjack-jackd2-dev libjack-jackd2-0 libdbus-1-dev

    - name: Build Release
      run: cargo build --release

    - name: Tests
      run: cargo test --release -- --nocapture

    - name: Test run
      run: cargo run --release -- --test-run

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: tessera_linux
        path: target/release/tessera

  build-macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2

    - name: Tests
      run: cargo test --release -- --nocapture

    - name: Test run
      run: cargo run --release -- --test-run

    - name: Build universal binary
      run: |
        rustup target add x86_64-apple-darwin
        cargo build --release --target x86_64-apple-darwin
        cargo build --release --target aarch64-apple-darwin
        mkdir -p artifacts
        lipo -create -output artifacts/tessera \
          target/x86_64-apple-darwin/release/tessera \
          target/aarch64-apple-darwin/release/tessera
        lipo -info artifacts/tessera
        ls -lh artifacts/

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: tessera_macos
        path: artifacts/tessera

  build-windows:

    runs-on: windows-latest
    env:
      CPAL_ASIO_DIR: ${{ github.workspace }}/asio

    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
    - name: Setup ASIO SDK
      run: |
        curl -L -o asio.zip https://www.steinberg.net/asiosdk
        7z x -oasio asio.zip
        move asio\*\* asio\
        # choco install asio4all  # Probably not necessary for now
        choco install llvm

    - name: Build
      run: cargo build --release

    - name: Tests
      run: cargo test --release -- --nocapture

    - name: Test run
      run: cargo run --release -- --test-run

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: tessera_windows
        path: target/release/tessera.exe
