name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Cache Linux audio packages
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: libasound2-dev libjack-jackd2-dev libjack-jackd2-0 libdbus-1-dev

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose -- --nocapture

    - name: Test run
      run: cargo run --release -- --test-run

  build-macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test verbose -- --nocapture

    - name: Test run
      run: cargo run --release -- --test-run

  build-windows:

    runs-on: windows-latest
    env:
      CPAL_ASIO_DIR: ${{ github.workspace }}/asio
      RUSTFLAGS: "-C target-feature=+avx2"

    steps:
    - uses: actions/checkout@v3
    - name: Setup ASIO SDK
      run: |
        curl -L -o asio.zip https://www.steinberg.net/asiosdk
        7z x -oasio asio.zip
        move asio\*\* asio\
        # choco install asio4all  # Probably not necessary for now
        choco install llvm

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test verbose -- --nocapture

    - name: Build Release
      run: cargo build --release

    - name: Test run
      run: cargo run --release -- --test-run

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: tessera_win
        path: |
          target/release/tessera.exe
          settings/
